apiVersion: app.jokimina.com/v1alpha1
kind: AppService
metadata:
  name: example-appservice
spec:
  # Add fields here
  size: 2
  image: nginx:1.7.9
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002